### ISSUE TITLE
infer.py时出现UNK

### ISSUE THREAD

**Issue by chendeming** [shibing624/pycorrector#120]
input:由我起开始做。
output:UNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNK

所有的output都是显示UNK，为什么？哪个步骤出了问题。

**Comment by shibing624** [comment]
same to https://github.com/shibing624/pycorrector/issues/112, 加大训练数据再训练，默认提供的数据集只是测试程序可以运行的。

**Comment by chendeming** [comment]
> same to #112, 加大训练数据再训练，默认提供的数据集只是测试程序可以运行的。

也就是说我的环境现在没有问题，是吗？

**Comment by debuluoyi** [comment]
请问下，出现这个问题，是英文tf版本问题吗？
RuntimeError: dataset.__iter__() is only supported when eager execution is enabled
作者实际开发时使用的是什么版本？谢谢

**Comment by shibing624** [comment]
tf2.0发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming <notifications@github.com>发送时间: 2020年1月19日 15:02收件人: shibing624/pycorrector <pycorrector@noreply.github.com>抄送: xuming <shibing624@126.com>, Comment <comment@noreply.github.com>主题: 回复：[shibing624/pycorrector] 在运行infer.py时错误 (#120)请问下，出现这个问题，是英文tf版本问题吗？
RuntimeError: dataset.iter() is only supported when eager execution is enabled
作者实际开发时使用的是什么版本？谢谢

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shibing624/pycorrector/issues/120?email_source=notifications\u0026email_token=ACOGLFXE5MGCBD4ILNNFTK3Q6P3I3A5CNFSM4J2LEEYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJKKUNA#issuecomment-575973940",
"url": "https://github.com/shibing624/pycorrector/issues/120?email_source=notifications\u0026email_token=ACOGLFXE5MGCBD4ILNNFTK3Q6P3I3A5CNFSM4J2LEEYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJKKUNA#issuecomment-575973940",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by hxyshare** [comment]
> > same to #112, 加大训练数据再训练，默认提供的数据集只是测试程序可以运行的。
> 
> 也就是说我的环境现在没有问题，是吗？加大到什么程度？

@chendeming @shibing624 Hi，是用的transformer模型吗，数据使用130w，大概要训练多少个step呢？
