### ISSUE TITLE
BERT model finetune的数据格式是什么样的？

### ISSUE THREAD

**Issue by nonva** [shibing624/pycorrector#137]
需要错误句子和正确句子pair对么？ 还是按人民日报数据以标题分段的格式就行？

**Comment by shibing624** [comment]
mlm模型，人民日报格式发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming <notifications@github.com>发送时间: 2020年3月26日 23:48收件人: shibing624/pycorrector <pycorrector@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[shibing624/pycorrector] BERT model finetune的数据格式是什么样的？ (#137)
需要错误句子和正确句子pair对么？ 还是按人民日报数据以标题分段的格式就行？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shibing624/pycorrector/issues/137",
"url": "https://github.com/shibing624/pycorrector/issues/137",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ZiYiWang-create** [comment]
您好，请问您知道bert微调的数据的格式了吗？

**Comment by shibing624** [comment]
见 bert/readme.md
