### ISSUE TITLE
三色云API 404

### ISSUE THREAD

**Issue by dancinglone** [shibing624/pycorrector#143]
你好，请问为什么三色云上的api访问404啦，是不是换了域名？

**Comment by dancinglone** [comment]
> 你好，请问为什么三色云上的api访问404啦，是不是换了域名？

访问地址为： https://www.borntowin.cn/api/v2/text/check

**Comment by shibing624** [comment]
没，是我还没写完发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming <notifications@github.com>发送时间: 2020年5月14日 18:11收件人: shibing624/pycorrector <pycorrector@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[shibing624/pycorrector] 三色云API 404 (#143)

你好，请问为什么三色云上的api访问404啦，是不是换了域名？

访问地址为： https://www.borntowin.cn/api/v2/text/check

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628535813",
"url": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628535813",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dancinglone** [comment]
你是指项目还没完成、未正式发布的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xuming"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 晚上6:39
收件人:&nbsp;"shibing624/pycorrector"<pycorrector@noreply.github.com&gt;;
抄送:&nbsp;"604055931"<604055931@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shibing624/pycorrector] 三色云API 404 (#143)





 没，是我还没写完发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming <notifications@github.com&gt;发送时间: 2020年5月14日 18:11收件人: shibing624/pycorrector <pycorrector@noreply.github.com&gt;抄送: Subscribed <subscribed@noreply.github.com&gt;主题: 回复：[shibing624/pycorrector] 三色云API 404 (#143)
 
 你好，请问为什么三色云上的api访问404啦，是不是换了域名？
 
 访问地址为： https://www.borntowin.cn/api/v2/text/check
 
 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
 [
 {
 "@context": "http://schema.org",
 "@type": "EmailMessage",
 "potentialAction": {
 "@type": "ViewAction",
 "target": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628535813",
 "url": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628535813",
 "name": "View Issue"
 },
 "description": "View this Issue on GitHub",
 "publisher": {
 "@type": "Organization",
 "name": "GitHub",
 "url": "https://github.com"
 }
 }
 ]

**Comment by shibing624** [comment]
嗯，api没写完，感觉没人用就没写发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming <notifications@github.com>发送时间: 2020年5月14日 18:40收件人: shibing624/pycorrector <pycorrector@noreply.github.com>抄送: xuming <shibing624@126.com>, Comment <comment@noreply.github.com>主题: 回复：[shibing624/pycorrector] 三色云API 404 (#143)
你是指项目还没完成、未正式发布的？









------------------&nbsp;原始邮件&nbsp;------------------

发件人:&nbsp;"xuming"<notifications@github.com&gt;;

发送时间:&nbsp;2020年5月14日(星期四) 晚上6:39

收件人:&nbsp;"shibing624/pycorrector"<pycorrector@noreply.github.com&gt;;

抄送:&nbsp;"604055931"<604055931@qq.com&gt;;"Author"<author@noreply.github.com&gt;;

主题:&nbsp;Re: [shibing624/pycorrector] 三色云API 404 (#143)











 没，是我还没写完发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming <notifications@github.com&gt;发送时间: 2020年5月14日 18:11收件人: shibing624/pycorrector <pycorrector@noreply.github.com&gt;抄送: Subscribed <subscribed@noreply.github.com&gt;主题: 回复：[shibing624/pycorrector] 三色云API 404 (#143)

 

 你好，请问为什么三色云上的api访问404啦，是不是换了域名？

 

 访问地址为： https://www.borntowin.cn/api/v2/text/check

 

 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

 [

 {

 "@context": "http://schema.org",

 "@type": "EmailMessage",

 "potentialAction": {

 "@type": "ViewAction",

 "target": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628535813",

 "url": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628535813",

 "name": "View Issue"

 },

 "description": "View this Issue on GitHub",

 "publisher": {

 "@type": "Organization",

 "name": "GitHub",

 "url": "https://github.com"

 }

 }

 ] 

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628549465",
"url": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628549465",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dancinglone** [comment]
有计划写一下吗?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xuming"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 晚上6:44
收件人:&nbsp;"shibing624/pycorrector"<pycorrector@noreply.github.com&gt;;
抄送:&nbsp;"604055931"<604055931@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shibing624/pycorrector] 三色云API 404 (#143)





 嗯，api没写完，感觉没人用就没写发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming <notifications@github.com&gt;发送时间: 2020年5月14日 18:40收件人: shibing624/pycorrector <pycorrector@noreply.github.com&gt;抄送: xuming <shibing624@126.com&gt;, Comment <comment@noreply.github.com&gt;主题: 回复：[shibing624/pycorrector] 三色云API 404 (#143)
 你是指项目还没完成、未正式发布的？
 
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 
 发件人:&amp;nbsp;"xuming"<notifications@github.com&amp;gt;;
 
 发送时间:&amp;nbsp;2020年5月14日(星期四) 晚上6:39
 
 收件人:&amp;nbsp;"shibing624/pycorrector"<pycorrector@noreply.github.com&amp;gt;;
 
 抄送:&amp;nbsp;"604055931"<604055931@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
 
 主题:&amp;nbsp;Re: [shibing624/pycorrector] 三色云API 404 (#143)
 
 
 
 
 
 
 
 
 
 
 
  没，是我还没写完发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming <notifications@github.com&amp;gt;发送时间: 2020年5月14日 18:11收件人: shibing624/pycorrector <pycorrector@noreply.github.com&amp;gt;抄送: Subscribed <subscribed@noreply.github.com&amp;gt;主题: 回复：[shibing624/pycorrector] 三色云API 404 (#143)
 
  
 
  你好，请问为什么三色云上的api访问404啦，是不是换了域名？
 
  
 
  访问地址为： https://www.borntowin.cn/api/v2/text/check
 
  
 
  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
 
  [
 
  {
 
  "@context": "http://schema.org",
 
  "@type": "EmailMessage",
 
  "potentialAction": {
 
  "@type": "ViewAction",
 
  "target": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628535813",
 
  "url": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628535813",
 
  "name": "View Issue"
 
  },
 
  "description": "View this Issue on GitHub",
 
  "publisher": {
 
  "@type": "Organization",
 
  "name": "GitHub",
 
  "url": "https://github.com"
 
  }
 
  }
 
  ] 
 
 —
 
 You are receiving this because you authored the thread.
 
 Reply to this email directly, view it on GitHub, or unsubscribe.
 
 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
 [
 {
 "@context": "http://schema.org",
 "@type": "EmailMessage",
 "potentialAction": {
 "@type": "ViewAction",
 "target": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628549465",
 "url": "https://github.com/shibing624/pycorrector/issues/143#issuecomment-628549465",
 "name": "View Issue"
 },
 "description": "View this Issue on GitHub",
 "publisher": {
 "@type": "Organization",
 "name": "GitHub",
 "url": "https://github.com"
 }
 }
 ]

**Comment by shibing624** [comment]
列在todo中
