### ISSUE TITLE
可以使用Albert模型吗

### ISSUE THREAD

**Issue by Jas-He** [shibing624/pycorrector#145]
查资料看到精简版bert在sentence级别的任务中已经完胜bert，想问下Albert可以适用于文本纠错吗。
不胜感激！

**Comment by shibing624** [comment]
可以适用发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming <notifications@github.com>发送时间: 2020年6月4日 20:02收件人: shibing624/pycorrector <pycorrector@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[shibing624/pycorrector] 可以使用Albert模型吗 (#145)
查资料看到精简版bert在sentence级别的任务中已经完胜bert，想问下Albert可以适用于文本纠错吗。
不胜感激！

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shibing624/pycorrector/issues/145",
"url": "https://github.com/shibing624/pycorrector/issues/145",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
